"""
report_generator.py

Builds a markdown incident summary from a parsed Wazuh alert.

If Airia is reachable (API key set + endpoint configured + call
succeeds), its explanation is included in the report. Otherwise the
script falls back to a simple, locally-generated summary so the
report is still useful without any AI dependency.
"""

import sys

from alert_parser import load_alert, parse_alert
from airia_client import AiriaClient, AiriaClientError


def local_fallback_summary(parsed: dict) -> str:
    """Basic rule-based summary used when the AI service is unavailable."""
    return (
        f"Alert **{parsed['rule_id']}** (level {parsed['rule_level']}) was "
        f"triggered on agent **{parsed['agent_name']}**.\n\n"
        f"This maps to MITRE technique **{parsed['mitre_id']}** "
        f"({parsed['mitre_technique']}) under the **{parsed['mitre_tactic']}** "
        f"tactic. The source IP **{parsed['src_ip']}** attempted to "
        f"authenticate as user **{parsed['dst_user']}**.\n\n"
        f"Recommended action: verify whether this source IP is expected, "
        f"check for repeated failed logins from the same host, and "
        f"consider blocking the IP if the activity is confirmed malicious."
    )


def build_prompt(parsed: dict) -> str:
    """Turn the parsed alert into a plain-language prompt for the Airia pipeline."""
    return (
        "Analyze this Wazuh security alert. Provide an Incident Summary, "
        "Recommended Actions, and a Severity rating.\n\n"
        f"Rule ID: {parsed['rule_id']}\n"
        f"Description: {parsed['rule_description']}\n"
        f"Level: {parsed['rule_level']}\n"
        f"MITRE ATT&CK ID: {parsed['mitre_id']}\n"
        f"MITRE Tactic: {parsed['mitre_tactic']}\n"
        f"MITRE Technique: {parsed['mitre_technique']}\n"
        f"Source IP: {parsed['src_ip']}\n"
        f"Target User: {parsed['dst_user']}\n"
        f"Agent: {parsed['agent_name']}\n"
        f"Timestamp: {parsed['timestamp']}\n"
        f"Raw Log: {parsed['full_log']}"
    )


def get_ai_summary(parsed: dict):
    """Try to get an AI-generated summary from Airia. Returns None on failure."""
    try:
        client = AiriaClient()
    except AiriaClientError as exc:
        print(f"[report_generator] AI client unavailable, using local fallback: {exc}")
        return None

    prompt = build_prompt(parsed)
    return client.analyze_alert(prompt)


def build_report(parsed: dict, ai_summary) -> str:
    """Assemble the final markdown incident report."""
    lines = [
        "# Incident Summary",
        "",
        f"- **Timestamp:** {parsed['timestamp']}",
        f"- **Agent:** {parsed['agent_name']}",
        f"- **Rule ID:** {parsed['rule_id']}",
        f"- **Rule Description:** {parsed['rule_description']}",
        f"- **Rule Level:** {parsed['rule_level']}",
        f"- **MITRE ID:** {parsed['mitre_id']}",
        f"- **MITRE Tactic:** {parsed['mitre_tactic']}",
        f"- **MITRE Technique:** {parsed['mitre_technique']}",
        f"- **Source IP:** {parsed['src_ip']}",
        f"- **Target User:** {parsed['dst_user']}",
        "",
        "## Raw Log",
        "```",
        parsed["full_log"],
        "```",
        "",
        "## Analysis",
    ]

    if ai_summary:
        lines.append(ai_summary)
        lines.append("")
        lines.append("*Analysis generated by Airia AI assistant.*")
    else:
        lines.append(local_fallback_summary(parsed))
        lines.append("")
        lines.append("*Local fallback summary (AI assistant not available).*")

    return "\n".join(lines)


def main():
    file_path = sys.argv[1] if len(sys.argv) > 1 else "sample_alert.json"

    alert = load_alert(file_path)
    parsed = parse_alert(alert)

    ai_summary = get_ai_summary(parsed)
    report = build_report(parsed, ai_summary)

    print(report)


if __name__ == "__main__":
    main()
